[alembic]
script_location = migrations
file_template = %%(year)d-%%(month).2d-%%(day).2d_%%(slug)s
prepend_sys_path = .
version_path_separator = os
# sqlalchemy.url is set from DATABASE_URL in alembic/env.py
